project:
  type: website
  render:
    - index.qmd
    - pagesweb/Video/tp.qmd
    - pagesweb/Map/tp.qmd
    - _build/html/index.html
website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "ATVM : Analyse du trafic velomagg de Montpellier"
  site-url: https://riwahachem.github.io/Projet_HAX712X/
  repo-url: https://github.com/riwahachem/Projet_HAX712X
  repo-actions: [source, issue]
  navbar:
    title: "ATVM"
    background : primary
    search : true
    left:
      - sidebar:map
      - sidebar:video
      - sidebar:docs
  sidebar:
    - id: map
      title: "Info trafic"
      collapse-level: 3
      contents: 
      - pagesweb/Map/tp.qmd
    - id: video
      title: "Visualisation"
      collapse-level: 3
      contents: 
      - pagesweb/Video/tp.qmd
    - id: docs
      title: "Documentation"
      collapse-level: 3
      contents: 
      - _build/html/index.html
format:
  html:
    execute:
      enabled: true
    theme: flatly
    #css: styles.css
    toc: true

  
