project:
  type: website
  resources:
    - "docs/_build/html/**"
    - "pagesweb/Map/carte_prediction_semaine/**"
    - "pagesweb/Map/carte_prediction_dimanche_heure"
    - "pagesweb/Map/carte_prediction_lundi_heure"
    - "pagesweb/Map/carte_prediction_mardi_heure"
    - "pagesweb/Map/carte_prediction_mercredi_heure"
    - "pagesweb/Map/carte_prediction_jeudi_heure"
    - "pagesweb/Map/carte_prediction_vendredi_heure"
    - "pagesweb/Map/carte_prediction_samedi_heure"

  render:
    - index.qmd
    - pagesweb/Video/tp.qmd
    - pagesweb/Map/tp.qmd
    - pagesweb/Map/tp2.qmd

website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "ATVM : Analyse du trafic velomagg de Montpellier"
  site-url: https://riwahachem.github.io/Projet_HAX712X/
  repo-url: https://github.com/riwahachem/Projet_HAX712X
  repo-actions: [source, issue]
  navbar:
    title: "ATVM"
    background : primary
    search : true
    left:
      - sidebar:map
      - sidebar:video
  sidebar:
    - id: map
      title: "Info trafic"
      collapse-level: 3
      contents: 
      - pagesweb/Map/tp.qmd
      - pagesweb/Map/tp2.qmd
    - id: video
      title: "Visualisation"
      collapse-level: 3
      contents: 
      - pagesweb/Video/tp.qmd
format:
  html:
    execute:
      enabled: true
    theme: flatly
    #css: styles.css
    toc: true
    
