project:
  type: website
  title: "Analyse du trafic velomagg de Montpellier"

site:
  title: "ATVM : Analyse du trafic velomagg de Montpellier"
  url: https://riwahachem.github.io/Projet_HAX712X/
  navbar:
    title: "ATVM"
  repo-url: https://github.com/riwahachem/Projet_HAX712X
  repo-actions: [source, issue]

format:
  html:
    theme: spacelab
    mermaid: {}
