---
title: "ATVM : Analyse du trafic VéloMagg de Montpellier"
output: html
execute:
  enabled: false
---

## 🚴‍♂️  Bienvenue sur **ATVM** !

**ATVM**  est un projet dédié à l’étude des données liées aux vélos du réseau VéloMagg de la Métropole de Montpellier. 

Dans le cadre de ce projet, nous nous sommes concentrés sur :  

1. **Collecte des données** :  
   Les données proviennent du service Open Data de de Montpellier Méditerranée Métropole, récupérées sous forme de fichiers CSV, JSON ou ZIP contenant les informations sur les trajets.

2. **Nettoyage et Prétraitement** :  
   - Correction de l’encodage des noms de stations
   - Filtrage des stations non pertinentes
   - Mise en forme des données horaires (jour, heure, etc.)

3. **Analyse** :  
   - Construction d’un graphe à partir des données OpenStreetMap via OSMNX
   - Calcul du plus court chemin entre stations pour évaluer la cohérence des trajets

4. **Prédictions** :  
   Utilisation de modèles statistiques pour prédire la fréquentation et la disponibilité des vélos selon le jour de la semaine et l’heure.


##  Installation

Pour installer le package ATVM, utilisez simplement la commande suivante dans votre terminal :  

```{python}
pip install git+https://github.com/riwahachem/Projet_HAX712X
```

Si vous souhaitez exécuter nos codes, des packages supplémentaires sont nécessaires, ils sont répertoriés dans le fichier requirements.txt :

```{python}
pip install -r requirements.txt
```

## Données et Ressources

- **Données brutes** : [OpenData](https://data.montpellier3m.fr)
- **OpenStreetMap** : [https://www.openstreetmap.org/](https://www.openstreetmap.org/)
- **Dépôt GitHub** : [ATVM sur GitHub](https://github.com/riwahachem/Projet_HAX712X)
- **Documentation Sphinx** : [vidéo](https://www.youtube.com/watch?v=BWIrhgCAae0&t=27s)  
- **Package json** : [vidéo](https://www.youtube.com/watch?v=gmfnN-dSVHM)
- **ChatGPT** : [OpenAI](https://chatgpt.com)

## Documentation : [Index](docs/_build/html/index.html)