name: Deploy Quarto Site

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Build Site
        uses: quarto-dev/quarto-actions/publish@v2 
        with:
          path: ./pagesweb
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
