name: documentation

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
      - uses: actions/setup-python@v3
      
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      
      - name: Sphinx build
        run: |
          sphinx-build doc _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: Documentation/_build/
          github_token: ${{ secrets.GITHUB_TOKEN }}
