name: documentation

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
      
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-autodoc-typehints
      
      - name: Sphinx build
        run: |
          cd Documentation 
          make html 

      - name: Create .nojekyll
        run: touch Documentation/_build/html/.nojekyll

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: Documentation/_build/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
